/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


#include <stdio.h>
#include <time.h>
#include ".\0002.h"

int main(int argc, char **argv)
{
    clock_t t;

    printf (" start : %d \n", ( int ) ( t= clock () ));

    int input = atoi(argv[1]);

    if (input > 0) 
    {
            IsEven(input);
            MyCode(input);
    } else
    {
        printf("Please enter a number bigger than 0!");
    }

    printf (" stop : %d \n", (int ) (t = clock () -t));

    printf (" Elapsed : %f seconds \n", ( double ) t / CLOCKS_PER_SEC ) ;

    return 0;
}